import 'package:app_vara/helpers/constants.dart';
import 'package:flutter/material.dart';

class RoutesData {
  final String start;
  final String end;
  final String title;
  final String description;
  final String linkApp;
  final String linkUrl;
  final String time;
  final bool easy;
  final bool medium;
  final bool hard;

  RoutesData({
    required this.start,
    required this.end,
    required this.title,
    required this.description,
    required this.linkApp,
    required this.linkUrl,
    required this.time,
    required this.easy,
    required this.medium,
    required this.hard,
  });
}


final List<RoutesData> routeDetails = [
  RoutesData(
    start: 'Rostiolo',
    end: 'Riparo Gilwell',
    title: 'Rostiolo - Riparo Gilwell',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: "https://www.komoot.com/it-it/tour/1370054647?ref=wtd&share_token=$komootToken",
    linkUrl: 'https://www.komoot.com/it-it/tour/1370054647/embed?profile=1&share_token=$komootToken',
    time: '3h 17m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Passo della Gava',
    title: 'Rostiolo - Passo della Gava',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370054589?ref=wtd&share_token=aa5F7JeodJ9lQCC1PsnGHQEPKn2eUBD98YNsumuUyeQAtkQ7AS',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370054589/embed?profile=1&share_token=aa5F7JeodJ9lQCC1PsnGHQEPKn2eUBD98YNsumuUyeQAtkQ7AS',
    time: '3h 307m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Riparo Padre Rino',
    title: 'Rostiolo - Riparo Padre Rino',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370054506?ref=wtd&share_token=avnP3vrmGCiTSMlS9SnoCn0tO6nDAZkhoPEgY6fgsyuJWxjlm3',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370054506/embed?profile=1&share_token=avnP3vrmGCiTSMlS9SnoCn0tO6nDAZkhoPEgY6fgsyuJWxjlm3',
    time: '2h 12m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Bric del Dente',
    title: 'Rostiolo - Bric del Dente',
    description: 'Percorso escursionistico per esperti. Buon allenamento richiesto. Sono richiesti passo sicuro, calzature robuste ed esperienza alpinistica.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370054410?ref=wtd&share_token=acHbpVH0GuLOYGnabJ4CKdLIIvT1ySCB4WOoy34I6CECUJrNti',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370054410/embed?profile=1&share_token=acHbpVH0GuLOYGnabJ4CKdLIIvT1ySCB4WOoy34I6CECUJrNti',
    time: '4h 1m',
    easy: false,
    medium: false,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Rifugio Pratorotondo',
    title: 'Rostiolo - Rifugio Pratorotondo',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370054324?ref=wtd&share_token=aN5ezX6mEd2nlOoliG4rWAYZ9DUsC8BO1zUy84g7FjYh002dM4',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370054324/embed?profile=1&share_token=aN5ezX6mEd2nlOoliG4rWAYZ9DUsC8BO1zUy84g7FjYh002dM4',
    time: '3h 12m',
    easy: false,
    medium: true,
    hard: true,
  ),
RoutesData(
    start: 'Rostiolo',
    end: 'Monte Reixa',
    title: 'Rostiolo - Monte Reixa',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370054124?ref=wtd&share_token=a5rEM0or9vqQMf3LlC9H4etowC5W63b7QNBefgdQ4y37tYGFGV',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370054124/embed?profile=1&share_token=a5rEM0or9vqQMf3LlC9H4etowC5W63b7QNBefgdQ4y37tYGFGV',
    time: '2h 15m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Rifugio Rifugio Argentea',
    title: 'Rostiolo - Rifugio Argentea',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370054053?ref=wtd&share_token=aBEiE4F6K8npY6rss9qG7eRM70QvRZORq0Q1ti9FqcaWbannZN',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370054053/embed?profile=1&share_token=aBEiE4F6K8npY6rss9qG7eRM70QvRZORq0Q1ti9FqcaWbannZN',
    time: '2h 09m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Monte Rama',
    title: 'Rostiolo - Monte Rama',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370053838?ref=wtd&share_token=a0idKoG21ESmsJWsBPwz2Sg0A5ceb3p418B2cd4cPF1So7bIN1',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370053838/embed?profile=1&share_token=a0idKoG21ESmsJWsBPwz2Sg0A5ceb3p418B2cd4cPF1So7bIN1',
    time: '3h 23m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Tiglio Casa Micula',
    title: 'Rostiolo - Tiglio Casa Micula',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370053757?ref=wtd&share_token=aUqx3KxfWpePvK2L9n3PTNTJL5XD9KXupHq0RWs8V8H7cIR8tZ',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370053757/embed?profile=1&share_token=aUqx3KxfWpePvK2L9n3PTNTJL5XD9KXupHq0RWs8V8H7cIR8tZ',
    time: '1h 06m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Torbiera Pianpaludo',
    title: 'Rostiolo - Torbiera Pianpaludo',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370053671?ref=wtd&share_token=ad124a9Ozs15nPe5YGf9OHzo1F1ABL6DCcyr8Om7Q9ctPvAvXf',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370053671/embed?profile=1&share_token=ad124a9Ozs15nPe5YGf9OHzo1F1ABL6DCcyr8Om7Q9ctPvAvXf',
    time: '1h 35m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Piani di Lerca',
    title: 'Rostiolo - Piani di Lerca',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370053621?ref=wtd&share_token=aGV7MN6M5b4DVS2bD61R6Z0m6dxEiUAtFvn1Cl2Y1PtS66a5jo',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370053621/embed?profile=1&share_token=aGV7MN6M5b4DVS2bD61R6Z0m6dxEiUAtFvn1Cl2Y1PtS66a5jo',
    time: '1h 44m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Rifugio Faiallo',
    title: 'Rostiolo - Rifugio Faiallo',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370053498?ref=wtd&share_token=aIDp6GJMbn4PDTRgF4fUyIP4C41soPiVWsPsK6KkR8nYPID8Hq',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370053498/embed?profile=1&share_token=aIDp6GJMbn4PDTRgF4fUyIP4C41soPiVWsPsK6KkR8nYPID8Hq',
    time: '2h 36m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Cima Faiallo',
    title: 'Rostiolo - Cima Faiallo',
    description: 'Percorso escursionistico per esperti. Buon allenamento richiesto. Sono richiesti passo sicuro, calzature robuste ed esperienza alpinistica.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370053402?ref=wtd&share_token=aIVj12fGibh2zbbqtNrFne98dYKKXjg7PiLulMYySoD2390TXD',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370053402/embed?profile=1&share_token=aIVj12fGibh2zbbqtNrFne98dYKKXjg7PiLulMYySoD2390TXD',
    time: '2h 50m',
    easy: false,
    medium: false,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Forte Geremia',
    title: 'Rostiolo - Forte Geremia',
    description: 'Percorso escursionistico per esperti. Buon allenamento richiesto. Sono richiesti passo sicuro, calzature robuste ed esperienza alpinistica.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370050700?ref=wtd&share_token=a3tK1I8qtaI9i9ov6veBLTrdhZIXwIOEBpT1oCRarcp0jh6hcl',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370050700/embed?profile=1&share_token=a3tK1I8qtaI9i9ov6veBLTrdhZIXwIOEBpT1oCRarcp0jh6hcl',
    time: '5h 4m',
    easy: false,
    medium: false,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Monte Sciguello',
    title: 'Rostiolo - Monte Sciguello',
    description: 'Percorso escursionistico intermedio. Buon allenamento richiesto. Sentieri prevalentemente accessibili. Richiesto passo sicuro.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370050290?ref=wtd&share_token=aL9etZUWinM7QgpPCvvyPuoTIZPU7NQHIznIveAD5d2YDozZnN',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370050290/embed?profile=1&share_token=aL9etZUWinM7QgpPCvvyPuoTIZPU7NQHIznIveAD5d2YDozZnN',
    time: '3h 30m',
    easy: false,
    medium: true,
    hard: true,
  ),
  RoutesData(
    start: 'Rostiolo',
    end: 'Area arrampicata Boulder',
    title: 'Rostiolo - Area arrampicata Boulder',
    description: 'Escursione facile. Adatto a ogni livello di allenamento. Sentieri facilmente percorribili. Adatto a ogni livello di abilità.',
    linkApp: 'https://www.komoot.com/it-it/tour/1370050190?ref=wtd&share_token=axK3DGQVEMAc0MgC5Gw8DP5y4soB156n7GPhvTbXJ6u96kfMix',
    linkUrl: 'https://www.komoot.com/it-it/tour/1370050190/embed?profile=1&share_token=axK3DGQVEMAc0MgC5Gw8DP5y4soB156n7GPhvTbXJ6u96kfMix',
    time: ' 14 min',
    easy: true,
    medium: true,
    hard: true,
  ),

];

